language: php
sudo: required
php:
    - 7.2
    - 7.3
    - 7.4
    - nightly
install:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev --no-interaction
script:
    - php vendor/bin/phpcbf -p
    - php vendor/bin/phpstan analyse -c phpstan.neon -l max src

jobs:
    allow_failures:
        - php: nightly
